package com.jlarrieux.ethereum_hourly_price;



import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;
import twitter4j.TwitterException;

import java.io.IOException;



/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@SpringBootApplication
@EnableScheduling
public class App {


    public static void main(String[] args) throws IOException, TwitterException {
        SpringApplication.run(App.class,args);

    }



}
